### ISSUE TITLE
For account security, newly registered WeChat accounts are unable to log in to WeChat for Web.

### ISSUE THREAD

**Issue by zhongqin0820** [liangjfblue/wxBot4g#1]
Hi, @liangjfblue Your project is awesome but I think code in [wcbot/wcbot.go#L359](https://github.com/liangjfblue/wxBot4g/blob/ecd791339de0a55becd68dd0047016af49d19c7d/wcbot/wcbot.go#L359) has a typo, should be `root != nil`? (As the title indicated the error I encountered.)

```go
root := doc.SelectElement("error")
if root != nil {
	logrus.Error(string(data))
	return false
}
```
Appreciate if you can explain what are `appKey`[config.yaml#L4](https://github.com/liangjfblue/wxBot4g/blob/ecd791339de0a55becd68dd0047016af49d19c7d/config.yaml#L4) and the two `appid`([wcbot/api.go#L162](https://github.com/liangjfblue/wxBot4g/blob/ecd791339de0a55becd68dd0047016af49d19c7d/wcbot/api.go#L162),[wcbot/wcbot.go#L232](https://github.com/liangjfblue/wxBot4g/blob/ecd791339de0a55becd68dd0047016af49d19c7d/wcbot/wcbot.go#L232)) in your project respectively? (Both Chinese and English are OK for me.)

Also, what is the LICENSE used?

**Comment by liangjfblue** [comment]
@zhongqin0820 
1.
youraccount cant not login, because the account registered after 2018 can't log in to web wechat, you can try login web wechat to make sure your account can login web wechat or not

2.
```
root := doc.SelectElement("error")
if root == nil {
	logrus.Error(string(data))
	return false
}
```

this no error, should return when root is nil, because when root is nil, the following code will be wrong

3. appid is wx782c26e4c19acffb, It's a fixed value. You can capture the interface of web wechat by yourself

**Comment by zhongqin0820** [comment]
Well, thanks to your reply but I am still confused. Since I don't have a valid account to verify it, I need to close this issue. All in all, really appreciate your reply.
